development:
  adapter: postgresql
  database: potimart
  username: chouette
  schema_search_path: chouette, potimart, public
  template: template_1

test:
  adapter: postgresql
  database: potimart_test
  username: chouette
  schema_search_path: chouette, potimart, public
  template: template_1

production:
  adapter: postgresql
  database: potimart
  username: chouette
  schema_search_path: chouette, potimart, public